//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traveloka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnhKhachSan
    {
        public int AnhId { get; set; }
        public Nullable<int> KhachSanId { get; set; }
        public string AnhKhachSan1 { get; set; }
    
        public virtual KhachSan KhachSan { get; set; }
    }
}
