//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traveloka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnhPhong
    {
        public int AnhPhongId { get; set; }
        public Nullable<int> PhongId { get; set; }
        public string AnhPhong1 { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
