//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traveloka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatPhong
    {
        public int DatPhongId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PhongId { get; set; }
        public Nullable<System.DateTime> NgayNhanPhong { get; set; }
        public Nullable<System.DateTime> NgayTraPhong { get; set; }
    
        public virtual Phong Phong { get; set; }
        public virtual User User { get; set; }
    }
}
