//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traveloka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanXet
    {
        public int NhanXetId { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayNhanXet { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> KhachSanId { get; set; }
        public Nullable<int> Diem { get; set; }
    
        public virtual KhachSan KhachSan { get; set; }
        public virtual User User { get; set; }
    }
}
